apiVersion: v1
kind: Pod
metadata:
  name: image-loader
  namespace: default
spec:
  nodeName: ip-10-102-40-148.ec2.internal
  restartPolicy: Never
  hostPID: true
  containers:
    - name: loader
      image: alpine:3.20
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: containerd-sock
      hostPath:
        path: /run/containerd/containerd.sock
        type: Socket
    - name: tmp
      emptyDir: {}
